restaurant/urls.py
"""restaurant的url设置"""

from django.conf.urls import url
from . import views

app_name = 'restaurant'

urlpatterns = [
    # 餐馆主页
    url(r'^$', views.index, name='index'),

    # 菜单主页
    url(r'^menu/$', views.menu, name='menu'),

    # 单个菜品的详细信息
    url(r'^menu/(?P<dish_id>\d+)/$', views.dish_detail, name='dish'),

    # 单个菜品的点菜界面
    url(r'menu/(?P<dish_id>\d+)/order/$', views.order_dish, name='dish_ordering'),

    # 显示账单
    url(r'bill/$', views.get_bill, name='bill'),
]

restaurant/models.py
from django.db import models

# Create your models here.


class Dish(models.Model):
    """餐馆里的一道菜"""
    name = models.CharField(max_length=10)
    prince = models.IntegerField(default=0)
    available = models.BooleanField(default=True)
    number_of_ordering = models.IntegerField(default=0)

    def __str__(self):
        """返回一道菜品的信息"""
        basic_txt = '菜名是：' + self.name + '，' + '价格是：' + str(self.prince)
        add_txt = '这道菜的销量是 :' + str(self.number_of_ordering)
        return basic_txt + '。' + add_txt


class Bill(models.Model):
    """
    记录单个客人的账单
    这个表的一个实例是，一道菜的详细订单信息，包括菜名，下单数量，客户对这道菜的要求
    整个表的内容是客人一次点单的信息，在结账完成之后，这个表清空
    """
    dish_name = models.CharField(max_length=10)
    dish_number = models.IntegerField(default=0)
    dish_require = models.CharField(max_length=50, default='无')

    def __str__(self):
        """显示信息"""
        txt = '菜名是：' + self.dish_name + ',' + '数量是:' + str(self.dish_number)
        add_txt = '客户的要求是：' + self.dish_require
        return txt + ',' + add_txt

restaurant/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy

# Create your views here.
from .models import Dish, Bill


def index(request):
    """显示主页"""
    return render(request, 'restaurant/homepage.html')


def menu(request):
    """显示所有的菜品"""
    dishes = Dish.objects.order_by('prince')
    content = {'dishes': dishes}
    return render(request, 'restaurant/menu.html', content)


def dish_detail(request, dish_id):
    """显示详细的菜品信息"""
    dish = Dish.objects.get(id=dish_id)
    name = dish.name
    price = dish.prince
    number = dish.number_of_ordering
    if number >= 3:
        txt = '这道菜卖的很好，是我们的招牌菜'
    else:
        txt = '这道菜是我们的新菜，你可以尝试一下'

    content = {'dish': dish, 'name': name, 'price': price, 'txt': txt}

    return render(request, 'restaurant/dish.html', content)


def order_dish(request, dish_id):
    """点单"""
    dish = Dish.objects.get(id=dish_id)  # 得到当前的菜

    if request.method != 'POST':
        """如果当前访问不是POST，显示表单页面"""
        name = dish.name
        content = {'name': name}
        return render(request, 'restaurant/order_dish.html', content)

    else:
        """客户提供点菜的要求"""
        number = request.POST['number']  # 客户点了几道这个菜
        require = request.POST['require']  # 客户对这道菜的要求
        dish.number_of_ordering = dish.number_of_ordering + int(number)  # 更新菜的销量数据
        dish.save()  # 保存到数据库
        bill = Bill(dish_name=dish.name, dish_number=number, dish_require=require)
        bill.save()  # 把点的菜保存到bill里
        return HttpResponseRedirect(reverse_lazy('restaurant:menu'))


def get_bill(request):
    """显示客户点的所有菜"""

    # 如果用户只是来查看这个页面
    if request.method != "POST":
        bills = Bill.objects.order_by('dish_name')
        content = {'bills': bills}
        return render(request, 'restaurant/bill.html', content)
    else:
        # 用户要结账，就清空bill这个表
        Bill.objects.all().delete()
        return HttpResponseRedirect(reverse_lazy('restaurant:index'))

restaurant/templates/restaurant/base.html
<p>
    <a href="{% url 'restaurant:index' %}">HomePage</a>
</p>

{% block content %}{% endblock content %}

restaurant/templates/restaurant/bill.html
{% extends 'restaurant/base.html' %}

{% block content %}

  <p>This is your bill, please check it</p>

  <ul>
    {% for bill in bills %}
        <li>
            <p>{{ bill.dish_name }}-{{ bill.dish_number }}-{{ bill.dish_require }}</p>
        </li>
    {% empty %}
      <li>No bill have been added yet.</li>
    {% endfor %}
  </ul>

  <form action="{% url 'restaurant:bill' %}" method="post">
    {% csrf_token %}
    <button name="submit">Settle the bill</button>
</form>
    <a href="{% url 'restaurant:menu' %}">Go back to menu</a>
{% endblock content %}

restaurant/templates/restaurant/dish.html
{% extends 'restaurant/base.html' %}

{% block content %}

<p>{{ name }}</p>
<p>{{ price }}元</p>
<p>{{ txt }}</p>

<a href="{% url 'restaurant:menu' %}">Back to menu</a> -
    <a href="{% url 'restaurant:dish_ordering' dish.id%}">Go to Order It</a>
{% endblock content %}

restaurant/templates/restaurant/homepage.html
{% extends 'restaurant/base.html' %}

{% block content %}

<p>Welcome to summer pig restaurant, you will enjoy the meal and have a good time</p>
    <a href="{% url 'restaurant:menu' %}">Go to the menu</a>

{% endblock content %}

restaurant/templates/restaurant/menu.html
{% extends 'restaurant/base.html' %}

{% block content %}

  <p>Dishes</p>

  <ul>
    {% for dish in dishes %}
        <li>
            <a href="{% url 'restaurant:dish' dish.id %}">{{ dish.name }}</a>
        </li>
    {% empty %}
      <li>No dish have been added yet.</li>
    {% endfor %}
  </ul>

    <a href="{% url 'restaurant:bill' %}">Go to my bill</a>

{% endblock content %}

restaurant/templates/restaurant/order_dish.html
{% extends 'restaurant/base.html' %}

{% block content %}
    {{ name }}
    <form action="" method="post" autocomplete="on">
    {% csrf_token %}
        number
        <input type="number" step="1" min="0" max="100" name="number" />
        <br/>
        require
        <input type="texy" name="require"/>
        <br/>
        <input type="submit" name="submit" value="confirm"/>
    </form>

    <a href="{% url 'restaurant:menu' %}">GO back to menu</a>

{% endblock content %}